In [0]:
import pandas as pd
import numpy as np

In [0]:
input1 = pd.DataFrame()


In [0]:
input1['input'] = [118997,
63756,
124972,
141795,
111429,
53536,
50522,
143985,
62669,
77518,
60164,
72698,
123145,
57693,
87138,
82831,
53289,
60110,
115660,
51217,
117781,
81556,
103963,
89000,
109330,
100487,
136562,
145020,
140554,
102425,
93333,
75265,
55764,
70093,
73800,
81349,
141055,
56441,
141696,
89544,
106152,
98674,
100882,
137932,
88008,
149027,
92767,
113740,
79971,
85741,
126630,
75626,
125042,
69237,
147069,
60786,
63751,
144363,
81873,
107230,
90789,
81655,
144004,
74536,
126675,
147470,
123359,
68081,
136423,
94629,
58263,
122420,
143933,
148528,
129120,
78391,
74289,
106795,
143640,
59108,
64462,
78216,
56113,
64708,
82372,
115231,
74229,
130979,
83590,
76666,
93156,
138450,
71077,
128048,
65476,
85804,
145692,
106836,
70016,
113158 ]

In [5]:
input1.head()

input
0  118997
1   63756
2  124972
3  141795
4  111429

In [0]:
input1['/3'] = input1['input']//3

In [0]:
input1['-2'] = input1['/3'] - 2

In [8]:
input1['-2'].sum()

3256114

In [0]:
input1['allfuel'] = np.NAN

In [10]:
for n in range(len(input1['-2'])):
  i = 0
  x= [input1['-2'][n]]
#  if (n//3)-2 > 0:
 #   x.append((n//3)-2)
  #  i= i+1
    #print(x[i]) 
  while (x[i]//3)-2 > 0:
    x.append((x[i]//3)-2)
#    print(x[i])
#    print('check')
    i = i+1
  else:
    input1['allfuel'][n] = sum(x)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [11]:
input1['allfuel'].sum()

4881302.0

# Day 2

In [0]:
# code = np.array([1,9,10,3,
# 2,3,11,0,
# 99,
# 30,40,50])

In [13]:
code = np.array([1,12,2,3,1,1,2,3,1,3,4,3,1,5,0,3,2,10,1,19,2,9,19,23,2,13,23,27,1,6,27,31,2,6,31,35,2,13,35,39,1,39,10,43,2,43,13,47,1,9,47,51,1,51,13,55,1,55,13,59,2,59,13,63,1,63,6,67,2,6,67,71,1,5,71,75,2,6,75,79,1,5,79,83,2,83,6,87,1,5,87,91,1,6,91,95,2,95,6,99,1,5,99,103,1,6,103,107,1,107,2,111,1,111,5,0,99,2,14,0,0,0,0,0])
code = code.reshape(-1,4)
code[0]

array([ 1, 12,  2,  3])

In [14]:
i = 0

for i in range(0,31):
  x = code[i][0]
  if x == 99:
    print('stopped')
  else:
    if x == 1:
      loc1 = (code[i][1])//4 
      item1 = (code[i][1]) - ((code[i][1])//4)*4
      loc2 = (code[i][2])//4 
      item2 = (code[i][2]) - ((code[i][2])//4)*4
      loc3 = (code[i][3])//4 
      item3 = (code[i][3]) - ((code[i][3])//4)*4
      code[loc3][item3] = code[loc1][item1] + code[loc2][item2]
      i = i+1
      # print(i)
    else:
      if x == 2:
        loc1 = (code[i][1])//4 
        item1 = (code[i][1]) - ((code[i][1])//4)*4
        loc2 = (code[i][2])//4 
        item2 = (code[i][2]) - ((code[i][2])//4)*4
        loc3 = (code[i][3])//4 
        item3 = (code[i][3]) - ((code[i][3])//4)*4
        code[loc3][item3] = code[loc1][item1] * code[loc2][item2]
        i = i+1

stopped


In [16]:
code.shape

(31, 4)

In [0]:
#(code[5][3]) - ((code[5][3])//4 )*4

In [18]:
code

array([[2890696,      12,       2,       2],
       [      1,       1,       2,       3],
       [      1,       3,       4,       3],
       [      1,       5,       0,       3],
       [      2,      10,       1,      48],
       [      2,       9,      19,     144],
       [      2,      13,      23,     720],
       [      1,       6,      27,     722],
       [      2,       6,      31,    1444],
       [      2,      13,      35,    7220],
       [      1,      39,      10,    7224],
       [      2,      43,      13,   36120],
       [      1,       9,      47,   36123],
       [      1,      51,      13,   36128],
       [      1,      55,      13,   36133],
       [      2,      59,      13,  180665],
       [      1,      63,       6,  180667],
       [      2,       6,      67,  361334],
       [      1,       5,      71,  361335],
       [      2,       6,      75,  722670],
       [      1,       5,      79,  722671],
       [      2,      83,       6, 1445342],
       [  

In [103]:
code = np.array([1,82,26,3,1,1,2,3,1,3,4,3,1,5,0,3,2,10,1,19,2,9,19,23,2,13,23,27,1,6,27,31,2,6,31,35,2,13,35,39,1,39,10,43,2,43,13,47,1,9,47,51,1,51,13,55,1,55,13,59,2,59,13,63,1,63,6,67,2,6,67,71,1,5,71,75,2,6,75,79,1,5,79,83,2,83,6,87,1,5,87,91,1,6,91,95,2,95,6,99,1,5,99,103,1,6,103,107,1,107,2,111,1,111,5,0,99,2,14,0,0,0,0,0])
code = code.reshape(-1,4)
code

array([[  1,  82,  26,   3],
       [  1,   1,   2,   3],
       [  1,   3,   4,   3],
       [  1,   5,   0,   3],
       [  2,  10,   1,  19],
       [  2,   9,  19,  23],
       [  2,  13,  23,  27],
       [  1,   6,  27,  31],
       [  2,   6,  31,  35],
       [  2,  13,  35,  39],
       [  1,  39,  10,  43],
       [  2,  43,  13,  47],
       [  1,   9,  47,  51],
       [  1,  51,  13,  55],
       [  1,  55,  13,  59],
       [  2,  59,  13,  63],
       [  1,  63,   6,  67],
       [  2,   6,  67,  71],
       [  1,   5,  71,  75],
       [  2,   6,  75,  79],
       [  1,   5,  79,  83],
       [  2,  83,   6,  87],
       [  1,   5,  87,  91],
       [  1,   6,  91,  95],
       [  2,  95,   6,  99],
       [  1,   5,  99, 103],
       [  1,   6, 103, 107],
       [  1, 107,   2, 111],
       [  1, 111,   5,   0],
       [ 99,   2,  14,   0],
       [  0,   0,   0,   0]])

In [104]:
i = 0

for i in range(0,31):
  x = code[i][0]
  if x == 99:
    print('stopped')
  else:
    if x == 1:
      loc1 = (code[i][1])//4 
      item1 = (code[i][1]) - ((code[i][1])//4)*4
      loc2 = (code[i][2])//4 
      item2 = (code[i][2]) - ((code[i][2])//4)*4
      loc3 = (code[i][3])//4 
      item3 = (code[i][3]) - ((code[i][3])//4)*4
      code[loc3][item3] = code[loc1][item1] + code[loc2][item2]
      i = i+1
      # print(i)
    else:
      if x == 2:
        loc1 = (code[i][1])//4 
        item1 = (code[i][1]) - ((code[i][1])//4)*4
        loc2 = (code[i][2])//4 
        item2 = (code[i][2]) - ((code[i][2])//4)*4
        loc3 = (code[i][3])//4 
        item3 = (code[i][3]) - ((code[i][3])//4)*4
        code[loc3][item3] = code[loc1][item1] * code[loc2][item2]
        i = i+1

stopped


In [105]:
code

array([[19690720,       82,       26,        2],
       [       1,        1,        2,        3],
       [       1,        3,        4,        3],
       [       1,        5,        0,        3],
       [       2,       10,        1,      328],
       [       2,        9,       19,      984],
       [       2,       13,       23,     4920],
       [       1,        6,       27,     4922],
       [       2,        6,       31,     9844],
       [       2,       13,       35,    49220],
       [       1,       39,       10,    49224],
       [       2,       43,       13,   246120],
       [       1,        9,       47,   246123],
       [       1,       51,       13,   246128],
       [       1,       55,       13,   246133],
       [       2,       59,       13,  1230665],
       [       1,       63,        6,  1230667],
       [       2,        6,       67,  2461334],
       [       1,        5,       71,  2461335],
       [       2,        6,       75,  4922670],
       [       1,   